---
- name: Obtener release de cada servidor
  hosts: all
  gather_facts: yes
  become: false

  tasks:
    - name: Crear línea CSV por host
      lineinfile:
        path: ./releases.csv
        line: "{{ inventory_hostname }},{{ ansible_distribution }},{{ ansible_distribution_version }},{{ ansible_distribution_release | default('') }}"
        create: yes
      delegate_to: localhost
